"""tometrics - Metrics for designs generated by topology optimization."""

__version__ = "v0.0.0"
__author__ = "Martin F. Schubert <mfschubert@gmail.com>"

from tometrics import metrics as metrics
from tometrics import shapes as shapes
